# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 'aks-private'

variables: 
- group: 'Azure-cloud-secrets'

steps:

- task: AzureCLI@2
  displayName: 'Import image to Azure Container Registry'
  inputs:
    azureSubscription: 'azure' # Specify your Azure subscription here
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      #az --version
      az aks get-credentials --resource-group terraform-rg --name aks-cluster
      kubectl get pods
      az acr login --name $(acr_registry) --expose-token

