# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 'aks-private'

variables: 
- group: 'Azure-cloud-secrets'

steps:

# - task: AzureCLI@2
#   displayName: 'Import image to Azure Container Registry'
#   inputs:
#     azureSubscription: 'azure'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#       # #az --version
#       # az aks get-credentials --resource-group terraform-rg --name aks-cluster
#       # kubectl get pods
#       az acr import --name $(acr_registry) --source $(SOURCE_REGISTRY)/$(CONTROLLER_IMAGE):$(CONTROLLER_TAG) --image $(CONTROLLER_IMAGE):$(CONTROLLER_TAG)
#       az acr import --name $(acr_registry) --source $(SOURCE_REGISTRY)/$(PATCH_IMAGE):$(PATCH_TAG) --image $(PATCH_IMAGE):$(PATCH_TAG)
#       az acr import --name $(acr_registry) --source $(SOURCE_REGISTRY)/$(DEFAULTBACKEND_IMAGE):$(DEFAULTBACKEND_TAG) --image $(DEFAULTBACKEND_IMAGE):$(DEFAULTBACKEND_TAG)
#       az acr login --name $(acr_registry) --expose-token

  - task: Bash@3
    inputs:
      filePath: 'ingress-controller.sh'
      arguments: 'nginx-ingress $(ACR_LOGIN_SERVER) ingress-basic'
      #workingDirectory: "ingress/"
